version: '2'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
    - "10.0.203.69:4160:4160"
    - "10.0.203.69:4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
    - nsqlookupd
    ports:
    - "10.0.203.69:4150:4150"
    - "10.0.203.69:4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
    - nsqlookupd
    ports:
    - "10.0.203.69:4171:4171"
